mqtt:
  enabled: false  # Set this to True if using MQTT for event triggers

detectors:
  memryx:
    type: memryx
    device: PCIe

# model:
#   model_type: yolov9
#   width: 640
#   height: 640
#   path: /memryx_models/yolov9/YOLO_v9_small_640_640_3_onnx.dfp
#   labelmap_path: /memryx_models/yolov9/labelmap.txt

# model:
#   model_type: yolonas
#   width: 320
#   height: 320
#   path: /memryx_models/yolo_nas/yolo_nas_s.dfp
#   labelmap_path: /memryx_models/yolo_nas/labelmap.txt

# model:
#   model_type: yolox
#   width: 640
#   height: 640
#   path: /memryx_models/yolox/YOLOX_640_640_3_onnx.dfp
#   labelmap_path: /memryx_models/yolox/labelmap.txt

model:
  model_type: ssd
  width: 320
  height: 320
  path: /memryx_models/ssdlite/SSDlite_MobileNet_v2_320_320_3_onnx.dfp
  labelmap_path: /memryx_models/ssdlite/labelmap.txt

cameras:
  Cam1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:NoPa$$word@192.168.56.22:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    detect:
      width: 640  
      height: 480
      fps: 30  
      enabled: true

    objects:
      track:
        - person
        - cup
        - bottle
        - keyboard
        - cell phone

    snapshots:
      enabled: false
      bounding_box: true
      retain:
        default: 1  # Keep snapshots for 2 days
    record:
      enabled: false
      retain:
        days: 1  # Keep recordings for 7 days
      alerts:
        retain:
          days: 1
      detections:
        retain:
          days: 1

version: 0.16-0

